import "swiper/css";
import "swiper/css/grid";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import "swiper/css/thumbs";
import "../app/global.css";

import "../assets/fonts/stylesheet.css";
import "../sass/main.scss";
import ApolloWrapper from "@/GraphQL/ApolloWrapper";
import Footer from "@/components/Common/Footer";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <ApolloWrapper>
                <body suppressHydrationWarning={true}>{children}</body>
                <Footer />
            </ApolloWrapper>
        </html>
    );
}
